{"Modified":"2017-08-29T01:31:00","Published":"2012-06-16T00:55:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":7.5,"cvss-time":"2017-08-29T01:31:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:P/A:P","cwe":"CWE-399","id":"CVE-2012-1502","impact":{"availability":"PARTIAL","confidentiality":"PARTIAL","integrity":"PARTIAL"},"last-modified":"2017-08-29T01:31:00","references":["http://lists.opensuse.org/opensuse-updates/2012-04/msg00027.html","http://secunia.com/advisories/48312","http://secunia.com/advisories/48332","http://secunia.com/advisories/48746","http://ubuntu.com/usn/usn-1395-1","http://www.debian.org/security/2012/dsa-2430","http://www.lsexperts.de/advisories/lse-2012-03-01.txt","http://www.osvdb.org/79892","https://exchange.xforce.ibmcloud.com/vulnerabilities/73857","https://security.gentoo.org/glsa/201507-09"],"refmap":{"debian":["DSA-2430"],"gentoo":["GLSA-201507-09"],"misc":["http://www.lsexperts.de/advisories/lse-2012-03-01.txt"],"osvdb":["79892"],"secunia":["48312","48332","48746"],"suse":["openSUSE-SU-2012:0487"],"ubuntu":["USN-1395-1"],"xf":["pypam-password-dos(73857)"]},"summary":"Double free vulnerability in the PyPAM_conv in PAMmodule.c in PyPam 0.5.0 and earlier allows remote attackers to cause a denial of service (application crash) or possibly execute arbitrary code via a NULL byte in a password string.","vulnerable_configuration":[{"id":"cpe:2.3:a:pypam:pypam:*:*:*:*:*:*:*:*","title":"cpe:2.3:a:pypam:pypam:*:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:pypam:pypam:*:*:*:*:*:*:*:*"]}