{"Modified":"2020-05-15T19:02:00","Published":"2020-05-14T21:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"LOCAL"},"assigner":"cve@mitre.org","capec":[],"cvss":4.6,"cvss-time":"2020-05-15T19:02:00","cvss-vector":"AV:L/AC:L/Au:N/C:P/I:P/A:P","cwe":"CWE-787","id":"CVE-2020-0102","impact":{"availability":"PARTIAL","confidentiality":"PARTIAL","integrity":"PARTIAL"},"last-modified":"2020-05-15T19:02:00","references":["https://source.android.com/security/bulletin/2020-05-01"],"refmap":{"misc":["https://source.android.com/security/bulletin/2020-05-01"]},"summary":"In GattServer::SendResponse of gatt_server.cc, there is a possible out of bounds write due to an incorrect bounds check. This could lead to local escalation of privilege with User execution privileges needed. User interaction is not needed for exploitation.Product: AndroidVersions: Android-8.0 Android-8.1 Android-9 Android-10Android ID: A-143231677","vulnerable_configuration":[{"id":"cpe:2.3:o:google:android:8.0:*:*:*:*:*:*:*","title":"cpe:2.3:o:google:android:8.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:google:android:8.1:*:*:*:*:*:*:*","title":"cpe:2.3:o:google:android:8.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:google:android:9.0:*:*:*:*:*:*:*","title":"cpe:2.3:o:google:android:9.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:google:android:10.0:*:*:*:*:*:*:*","title":"cpe:2.3:o:google:android:10.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:o:google:android:8.0:*:*:*:*:*:*:*","cpe:2.3:o:google:android:8.1:*:*:*:*:*:*:*","cpe:2.3:o:google:android:9.0:*:*:*:*:*:*:*","cpe:2.3:o:google:android:10.0:*:*:*:*:*:*:*"]}