{"Modified":"2020-08-24T17:37:00","Published":"2018-10-23T16:29:00","access":{"authentication":"NONE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4.3,"cvss-time":"2020-08-24T17:37:00","cvss-vector":"AV:N/AC:M/Au:N/C:N/I:P/A:N","cwe":"NVD-CWE-noinfo","id":"CVE-2018-18603","impact":{"availability":"NONE","confidentiality":"NONE","integrity":"PARTIAL"},"last-modified":"2020-08-24T17:37:00","references":["https://exchange.xforce.ibmcloud.com/vulnerabilities/151867","https://github.com/sandboxescape/360-3.5.0.1033-Sandbox-Escape-Exploit/"],"refmap":{"misc":["https://github.com/sandboxescape/360-3.5.0.1033-Sandbox-Escape-Exploit/"]},"summary":"** DISPUTED ** 360 Total Security 3.5.0.1033 allows a Sandbox Escape via an \"import os\" statement, followed by os.system(\"CMD\") or os.system(\"PowerShell\"), within a .py file. NOTE: the vendor's position is that this cannot be categorized as a vulnerability, although it is a security-related issue.","vulnerable_configuration":[{"id":"cpe:2.3:a:360totalsecurity:360_total_security:3.5.0.1033:*:*:*:*:*:*:*","title":"cpe:2.3:a:360totalsecurity:360_total_security:3.5.0.1033:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:360totalsecurity:360_total_security:3.5.0.1033:*:*:*:*:*:*:*"]}