{"Modified":"2019-10-03T00:03:00","Published":"2019-04-02T20:29:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[{"id":"586","name":"Object Injection","prerequisites":"The target application must unserialize data before validation.","related_weakness":["502"],"solutions":"Implementation: Keep session state on the server, when possible.","summary":"An adversary attempts to exploit an application by injecting additional, malicious content during its processing of serialized objects. Developers leverage serialization in order to convert data or state into a static, binary format for saving to disk or transferring over a network. These objects are then deserialized when needed to recover the data/state. By injecting a malformed object into a vulnerable application, an adversary can potentially compromise the application by manipulating the deserialization process. This can result in a number of unwanted outcomes, including remote code execution."}],"cvss":5,"cvss-time":"2019-10-03T00:03:00","cvss-vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","cwe":"CWE-502","id":"CVE-2018-12680","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2019-10-03T00:03:00","references":["https://github.com/Tanganelli/CoAPthon/issues/135"],"refmap":{"misc":["https://github.com/Tanganelli/CoAPthon/issues/135"]},"summary":"The Serialize.deserialize() method in CoAPthon 3.1, 4.0.0, 4.0.1, and 4.0.2 mishandles certain exceptions, leading to a denial of service in applications that use this library (e.g., the standard CoAP server, CoAP client, CoAP reverse proxy, example collect CoAP server and client) when they receive crafted CoAP messages.","vulnerable_configuration":[{"id":"cpe:2.3:a:coapthon_project:coapthon:3.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:coapthon_project:coapthon:3.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:coapthon_project:coapthon:4.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:coapthon_project:coapthon:4.0.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:coapthon_project:coapthon:4.0.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:coapthon_project:coapthon:4.0.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:coapthon_project:coapthon:4.0.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:coapthon_project:coapthon:4.0.2:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:coapthon_project:coapthon:3.1:*:*:*:*:*:*:*","cpe:2.3:a:coapthon_project:coapthon:4.0.0:*:*:*:*:*:*:*","cpe:2.3:a:coapthon_project:coapthon:4.0.1:*:*:*:*:*:*:*","cpe:2.3:a:coapthon_project:coapthon:4.0.2:*:*:*:*:*:*:*"]}