{"Modified":"2023-05-03T11:15:00","Published":"2021-03-15T18:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[{"id":"459","name":"Creating a Rogue Certification Authority Certificate","prerequisites":"Certification Authority is using the MD5 hash function to generate the certificate hash to be signed","related_weakness":["290","295","327"],"solutions":"Certification Authorities need to stop using the weak collision prone MD5 hashing algorithm to hash the certificates that they are about to sign. Instead they should be using stronger hashing functions such as SHA-256 or SHA-512.","summary":"An adversary exploits a weakness in the MD5 hash algorithm (weak collision resistance) to generate a certificate signing request (CSR) that contains collision blocks in the \"to be signed\" part. The adversary specially crafts two different, but valid X.509 certificates that when hashed with the MD5 algorithm would yield the same value. The adversary then sends the CSR for one of the certificates to the Certification Authority which uses the MD5 hashing algorithm. That request is completely valid and the Certificate Authority issues an X.509 certificate to the adversary which is signed with its private key. An adversary then takes that signed blob and inserts it into another X.509 certificate that the attacker generated. Due to the MD5 collision, both certificates, though different, hash to the same value and so the signed blob works just as well in the second certificate. The net effect is that the adversary's second X.509 certificate, which the Certification Authority has never seen, is now signed and validated by that Certification Authority. To make the attack more interesting, the second certificate could be not just a regular certificate, but rather itself a signing certificate. Thus the adversary is able to start their own Certification Authority that is anchored in its root of trust in the legitimate Certification Authority that has signed the attackers' first X.509 certificate. If the original Certificate Authority was accepted by default by browsers, so will now the Certificate Authority set up by the adversary and of course any certificates that it signs. So the adversary is now able to generate any SSL certificates to impersonate any web server, and the user's browser will not issue any warning to the victim. This can be used to compromise HTTPS communications and other types of systems where PKI and X.509 certificates may be used (e.g., VPN, IPSec)."}],"cvss":6.4,"cvss-time":"2023-05-03T11:15:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:P/A:N","cwe":"CWE-295","id":"CVE-2021-28363","impact":{"availability":"NONE","confidentiality":"PARTIAL","integrity":"PARTIAL"},"last-modified":"2023-05-03T11:15:00","references":["https://github.com/urllib3/urllib3/commits/main","https://pypi.org/project/urllib3/1.26.4/","https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0","https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4S65ZQVZ2ODGB52IC7VJDBUK4M5INCXL/","https://security.gentoo.org/glsa/202107-36","https://www.oracle.com/security-alerts/cpuoct2021.html","https://security.gentoo.org/glsa/202305-02"],"summary":"The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.","vulnerable_configuration":[{"id":"cpe:2.3:a:python:urllib3:1.26.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:python:urllib3:1.26.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python:urllib3:1.26.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:python:urllib3:1.26.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python:urllib3:1.26.3:*:*:*:*:*:*:*","title":"cpe:2.3:a:python:urllib3:1.26.3:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*","title":"cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:oracle:peoplesoft_enterprise_peopletools:8.59:*:*:*:*:*:*:*","title":"cpe:2.3:a:oracle:peoplesoft_enterprise_peopletools:8.59:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:python:urllib3:1.26.0:*:*:*:*:*:*:*","cpe:2.3:a:python:urllib3:1.26.1:*:*:*:*:*:*:*","cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*","cpe:2.3:a:python:urllib3:1.26.3:*:*:*:*:*:*:*","cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*","cpe:2.3:a:oracle:peoplesoft_enterprise_peopletools:8.59:*:*:*:*:*:*:*"]}