{"Modified":"2021-11-26T20:01:00","Published":"2021-11-03T17:15:00","access":{"authentication":"NONE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4.3,"cvss-time":"2021-11-26T20:01:00","cvss-vector":"AV:N/AC:M/Au:N/C:N/I:N/A:P","cwe":"CWE-476","id":"CVE-2021-27836","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2021-11-26T20:01:00","references":["https://github.com/libxls/libxls/issues/94","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SFOE4Z6T46LA47VXWUVET4ELXRZQ3BWB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Y6XOTFEOCHYKZAFCB6H3KNIIFJ3UFV7V/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5D7XXCVFYRRMI4ENXYSD3MZEBS6SMI7E/"],"summary":"An issue was discoverered in in function xls_getWorkSheet in xls.c in libxls 1.6.2, allows attackers to cause a denial of service, via a crafted XLS file.","vulnerable_configuration":[{"id":"cpe:2.3:a:libxls_project:libxls:1.6.2:-:*:*:*:*:*:*","title":"cpe:2.3:a:libxls_project:libxls:1.6.2:-:*:*:*:*:*:*"},{"id":"cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*","title":"cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*","title":"cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:fedoraproject:fedora:35:*:*:*:*:*:*:*","title":"cpe:2.3:o:fedoraproject:fedora:35:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:libxls_project:libxls:1.6.2:-:*:*:*:*:*:*","cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*","cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*","cpe:2.3:o:fedoraproject:fedora:35:*:*:*:*:*:*:*"]}