{"Modified":"2022-10-28T22:32:00","Published":"2022-06-24T16:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"psirt@us.ibm.com","capec":[{"id":"1","name":"Accessing Functionality Not Properly Constrained by ACLs","prerequisites":"The application must be navigable in a manner that associates elements (subsections) of the application with ACLs. The various resources, or individual URLs, must be somehow discoverable by the attacker The administrator must have forgotten to associate an ACL or has associated an inappropriately permissive ACL with a particular navigable resource.","related_weakness":["276","285","434","693","721","732"],"solutions":"In a more general setting, the administrator must mark every resource besides the ones supposed to be exposed to the user as accessible by a role impossible for the user to assume. The default security setting must be to deny access and then grant access only to those resources intended by business logic.","summary":"In applications, particularly web applications, access to functionality is mitigated by an authorization framework. This framework maps Access Control Lists (ACLs) to elements of the application's functionality; particularly URL's for web apps. In the case that the administrator failed to specify an ACL for a particular element, an attacker may be able to access it with impunity. An attacker with the ability to access functionality not properly constrained by ACLs can obtain sensitive information and possibly compromise the entire application. Such an attacker can access resources that must be available only to users at a higher privilege level, can access management sections of the application, or can run queries for data that they otherwise not supposed to."}],"cvss":7.5,"cvss-time":"2022-10-28T22:32:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:P/A:P","cwe":"CWE-434","id":"CVE-2021-38945","impact":{"availability":"PARTIAL","confidentiality":"PARTIAL","integrity":"PARTIAL"},"last-modified":"2022-10-28T22:32:00","references":["https://www.ibm.com/support/pages/node/6597241","https://exchange.xforce.ibmcloud.com/vulnerabilities/211238","https://security.netapp.com/advisory/ntap-20220729-0002/"],"summary":"IBM Cognos Analytics 11.2.1, 11.2.0, and 11.1.7 could allow a remote attacker to upload arbitrary files, caused by improper content validation. IBM X-Force ID: 211238.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:-:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:-:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.2:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.3:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.3:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.4:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.4:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.5:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.5:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.6:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.6:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack1:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack1:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack2:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack2:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack3:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack3:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack4:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack4:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.2.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.2.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.2.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.2.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:netapp:oncommand_insight:-:*:*:*:*:*:*:*","title":"cpe:2.3:a:netapp:oncommand_insight:-:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:cognos_analytics:11.1.7:-:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.1:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.2:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.3:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.4:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.5:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.6:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.7:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack1:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack2:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack3:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack4:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.2.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.2.1:*:*:*:*:*:*:*","cpe:2.3:a:netapp:oncommand_insight:-:*:*:*:*:*:*:*"]}