{"Modified":"2022-11-01T17:52:00","Published":"2022-10-31T19:15:00","access":{},"assigner":"cve@mitre.org","capec":[],"cvss":null,"cwe":"CWE-787","id":"CVE-2022-44079","impact":{},"last-modified":"2022-11-01T17:52:00","references":["https://github.com/zrax/pycdc/issues/291"],"summary":"pycdc commit 44a730f3a889503014fec94ae6e62d8401cb75e5 was discovered to contain a stack overflow via the component __sanitizer::StackDepotBase<__sanitizer::StackDepotNode.","vulnerable_configuration":[{"id":"cpe:2.3:a:pycdc_project:pycdc:*:*:*:*:*:*:*:*","title":"cpe:2.3:a:pycdc_project:pycdc:*:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:pycdc_project:pycdc:*:*:*:*:*:*:*:*"]}