{"Modified":"2022-06-02T14:15:00","Published":"2019-07-17T15:15:00","access":{"authentication":"NONE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4.3,"cvss-time":"2022-06-02T14:15:00","cvss-vector":"AV:N/AC:M/Au:N/C:N/I:N/A:P","cwe":"CWE-835","id":"CVE-2019-13453","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2022-06-02T14:15:00","references":["https://salvatoresecurity.com/fun-with-fuzzers-how-i-discovered-three-vulnerabilities-part-2-of-3/","https://sourceforge.net/p/zipios/news/2019/07/version-017-cve-/","http://www.securityfocus.com/bid/109282","https://lists.debian.org/debian-lts-announce/2022/05/msg00041.html"],"refmap":{"bid":["109282"],"confirm":["https://sourceforge.net/p/zipios/news/2019/07/version-017-cve-/"],"misc":["https://salvatoresecurity.com/fun-with-fuzzers-how-i-discovered-three-vulnerabilities-part-2-of-3/"]},"summary":"Zipios before 0.1.7 does not properly handle certain malformed zip archives and can go into an infinite loop, causing a denial of service. This is related to zipheadio.h:readUint32() and zipfile.cpp:Zipfile::Zipfile().","vulnerable_configuration":[{"id":"cpe:2.3:a:zipios_project:zipios:0.1.5:*:*:*:*:*:*:*","title":"cpe:2.3:a:zipios_project:zipios:0.1.5:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:zipios_project:zipios:0.1.6:*:*:*:*:*:*:*","title":"cpe:2.3:a:zipios_project:zipios:0.1.6:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:zipios_project:zipios:0.1.5:*:*:*:*:*:*:*","cpe:2.3:a:zipios_project:zipios:0.1.6:*:*:*:*:*:*:*"]}