{"Modified":"2020-08-24T17:37:00","Published":"2019-07-19T22:15:00","access":{"authentication":"SINGLE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":9,"cvss-time":"2020-08-24T17:37:00","cvss-vector":"AV:N/AC:L/Au:S/C:C/I:C/A:C","cwe":"NVD-CWE-noinfo","id":"CVE-2019-11990","impact":{"availability":"COMPLETE","confidentiality":"COMPLETE","integrity":"COMPLETE"},"last-modified":"2020-08-24T17:37:00","references":["https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbhf03937en_us"],"refmap":{"confirm":["https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbhf03937en_us"]},"summary":"Security vulnerabilities in HPE UIoT versions 1.6, 1.5, 1.4.2, 1.4.1, 1.4.0, and 1.2.4.2 could allow unauthorized remote access and access to sensitive data. HPE has addressed this issue in HPE UIoT: * For customers with release UIoT 1.6, fixes are made available with 1.6 RP603 * For customers with release UIoT 1.5, fixes are made available with 1.5 RP503 HF3 * For customers with release older than 1.5, such as 1.4.0, 1.4.1, 1.4.2 and 1.2.4.2, the resolution will be to upgrade to 1.5 RP503 HF3 or 1.6 RP603 Customers are requested to upgrade to the updated versions or contact HPE support for further assistance.","vulnerable_configuration":[{"id":"cpe:2.3:a:hp:universal_internet_of_things:1.2.4.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:hp:universal_internet_of_things:1.2.4.2:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:hp:universal_internet_of_things:1.4.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:hp:universal_internet_of_things:1.4.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:hp:universal_internet_of_things:1.4.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:hp:universal_internet_of_things:1.4.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:hp:universal_internet_of_things:1.4.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:hp:universal_internet_of_things:1.4.2:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:hp:universal_internet_of_things:1.5:*:*:*:*:*:*:*","title":"cpe:2.3:a:hp:universal_internet_of_things:1.5:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:hp:universal_internet_of_things:1.6:*:*:*:*:*:*:*","title":"cpe:2.3:a:hp:universal_internet_of_things:1.6:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:hp:universal_internet_of_things:1.2.4.2:*:*:*:*:*:*:*","cpe:2.3:a:hp:universal_internet_of_things:1.4.0:*:*:*:*:*:*:*","cpe:2.3:a:hp:universal_internet_of_things:1.4.1:*:*:*:*:*:*:*","cpe:2.3:a:hp:universal_internet_of_things:1.4.2:*:*:*:*:*:*:*","cpe:2.3:a:hp:universal_internet_of_things:1.5:*:*:*:*:*:*:*","cpe:2.3:a:hp:universal_internet_of_things:1.6:*:*:*:*:*:*:*"]}