{"Modified":"2020-08-24T17:37:00","Published":"2019-07-27T19:15:00","access":{"authentication":"NONE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4.3,"cvss-time":"2020-08-24T17:37:00","cvss-vector":"AV:N/AC:M/Au:N/C:N/I:N/A:P","cwe":"CWE-416","id":"CVE-2019-14294","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2020-08-24T17:37:00","references":["https://forum.xpdfreader.com/viewtopic.php?f=3&t=41851","https://github.com/TeamSeri0us/pocs/tree/master/xpdf/4.01.01"],"refmap":{"misc":["https://forum.xpdfreader.com/viewtopic.php?f=3&t=41851","https://github.com/TeamSeri0us/pocs/tree/master/xpdf/4.01.01"]},"summary":"An issue was discovered in Xpdf 4.01.01. There is a use-after-free in the function JPXStream::fillReadBuf at JPXStream.cc, due to an out of bounds read.","vulnerable_configuration":[{"id":"cpe:2.3:a:glyphandcog:xpdfreader:4.01.01:*:*:*:*:*:*:*","title":"cpe:2.3:a:glyphandcog:xpdfreader:4.01.01:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:glyphandcog:xpdfreader:4.01.01:*:*:*:*:*:*:*"]}