{"Modified":"2020-02-04T23:15:00","Published":"2019-11-21T20:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":5,"cvss-time":"2020-02-04T23:15:00","cvss-vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","cwe":"CWE-369","id":"CVE-2019-5637","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2020-02-04T23:15:00","references":["https://blog.rapid7.com/2019/10/08/r7-2019-32-denial-of-service-vulnerabilities-in-beckhoff-twincat-plc-environment-fixed/","https://download.beckhoff.com/download/Document/product-security/Advisories/advisory-2019-007.pdf"],"refmap":{"confirm":["https://download.beckhoff.com/download/Document/product-security/Advisories/advisory-2019-007.pdf"],"misc":["https://blog.rapid7.com/2019/10/08/r7-2019-32-denial-of-service-vulnerabilities-in-beckhoff-twincat-plc-environment-fixed/"]},"summary":"When Beckhoff TwinCAT is configured to use the Profinet driver, a denial of service of the controller could be reached by sending a malformed UDP packet to the device. This issue affects TwinCAT 2 version 2304 (and prior) and TwinCAT 3.1 version 4204.0 (and prior).","vulnerable_configuration":[{"id":"cpe:2.3:o:beckhoff:twincat:3.1.4022.30:*:*:*:*:*:*:*","title":"cpe:2.3:o:beckhoff:twincat:3.1.4022.30:*:*:*:*:*:*:*"},{"id":"cpe:2.3:h:beckhoff:twincat_cx2030:-:*:*:*:*:*:*:*","title":"cpe:2.3:h:beckhoff:twincat_cx2030:-:*:*:*:*:*:*:*"},{"id":"cpe:2.3:h:beckhoff:twincat_cx5140:-:*:*:*:*:*:*:*","title":"cpe:2.3:h:beckhoff:twincat_cx5140:-:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:beckhoff:twincat:3.1.4022.29:*:*:*:*:*:*:*","title":"cpe:2.3:o:beckhoff:twincat:3.1.4022.29:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:o:beckhoff:twincat:3.1.4022.30:*:*:*:*:*:*:*","cpe:2.3:o:beckhoff:twincat:3.1.4022.29:*:*:*:*:*:*:*"]}